# Generated by Django 3.2.9 on 2022-01-08 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_apointment_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RenameField(
            model_name='apointment',
            old_name='date',
            new_name='dateStart',
        ),
        migrations.RemoveField(
            model_name='apointment',
            name='is_canceld',
        ),
        migrations.AddField(
            model_name='apointment',
            name='dateEnd',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
